### ISSUE TITLE
ProtonUp-Qt v2.11.1 AppImage does not bring up the GUI

### ISSUE THREAD

**Issue by 123Daktary** [DavidoTek/ProtonUp-Qt#480]
**Describe the bug**  
The AppImage version of ProtonUp-Qt v2.11.1 does not open the GUI. Process starts and runs until a point then remains hanging in background.

**To Reproduce**  
1. Download version v2.11.1 of the ProtonUp-Qt Applimage from the [releases page](https://github.com/DavidoTek/ProtonUp-Qt/releases/tag/v2.11.1)
2. Set downloaded AppImage as executable
3. Run the AppImage from a terminal emulator

**Expected behavior**  
After executing the application via terminal or AppImage manager app, the ProtonUp-Qt GUI should be visible.

**Desktop:**  
 - **Platform**: PC
 - **System**: Arch Linux x86_64, 6.12.10-arch1-1 kernel, running Hyprland 0.46.2 (Wayland)
 - **Version**: ProtonUp-Qt 2.11.1
 - **How did you install ProtonUp-Qt?**: AppImage

**Additional context**  
The apps seems to start normally when executing from the console but after a short while it just freezes (please refer to the terminal output). If I look it up under `htop` there isn't any obvious activity. I left the app running for a few hours and nothing happened. Trying to close the process with `CTRL+C` does nothing. The only way to close the application is to terminate the `python3 -m pupgui2` process that is running in the background.

Running from a AppImage manager like Gear Lever does not show any info. If you try to re-run the application you will get a notification saying that the app is already running. That's why I'm posting the terminal output as it may be more relevant.

I tried running all available versions on a secondary installation using pretty much the same package base. The AppImage version gets stuck there as well. The Flatpak version and the `protonup-qt` AUR version work as intended.

This is a minor issue for me as the older version still works. Just wanted to let you know that there seems to be an issue with the current AppImage build.

**Terminal output**  
- Output for v2.11.1:
```
ProtonUp-Qt 2.11.1 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0], PySide 6.8.1
Platform: Arch rolling Linux-6.12.10-arch1-1-x86_64-with-glibc2.40
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod RTSP Proton
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine Bleeding Edge)
Loaded ctmod Wine Tkg (Wine Master)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
```
At this point the output freezes and the app remains stuck in the background.

- Output for v2.10.2:
```
ProtonUp-Qt 2.10.0 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0], PySide 6.7.2
Platform: Arch rolling Linux-6.12.10-arch1-1-x86_64-with-glibc2.40
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine Bleeding Edge)
Loaded ctmod Wine Tkg (Wine Master)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
Gamepad error: 'NoneType' object has no attribute 'get_char_device_path'
```
At this point the GUI shows up and everything is working fine.

**Comment by nPHYN1T3** [comment]
Same issue here. 2.10 was working fine just a bit ago before I decided to check for an update. The initial 2.11 launch it complained there was a second instance running but when I checked processes only 2.11 was running and it was hung. After killing it twice and the same complaint the next launch it did as OP says. Some basic version info, Loaded list then nothing...just hangs with no GUI.

**Comment by Techwolf** [comment]
I was just hit with this. The same version ran ok last week. The only difference is I changed my video card from nvidia to AMD.

**Comment by sonic2kk** [comment]
I was traveling and have not updated my system in about 18 days, but v2.11.1 AppImage works fine for me on Arch Linux w/ KDE Plasma Wayland. I am also running the latest Steam Client Beta.

I suspect this is some kind of AppImage packaging issue though, since the Flatpak and running from source works (i.e. AUR packages). I wonder what the problem is though. When I update my system, if the problem persists, I'll report back.

**Comment by sonic2kk** [comment]
After updating my system, things are still working fine with the v2.11.1 AppImage. Not sure what the issue could be then.

OS: Arch Linux w/ KDE Plasma Wayland 6.2.5
CPU: Ryzen 3700X
GPU: AMD 7900XTX
Kernel: 6.12.10 Zen Kernel

**Comment by ToRRent1812** [comment]
on my end, it says, it's missing libgthread-2_0-0 so I just downloaded it with package manager.

**Comment by sonic2kk** [comment]
We had a similar issue before where we had to include `libxcb-cursor0` in the AppImage (#382), but I think this was after an AppImage Ubuntu version bump. In this case, I don't think anything like that has changed between v2.10.2 and v2.11.1.

Perhaps distributions don't include this (anymore?) and that's why this is coming up, and I happened to get lucky and have it on my system. I'll check to see what includes this library later and where I might have it from (my Arch install is 6+ years old, it easily could've been picked up somewhere along the way if it's not standard).

**Comment by nPHYN1T3** [comment]
Arch only includes what you select yourself. As for Arch based "Distrobutions" (Endeavor, Garuda, Manjaro, etc) those will typically kitchen sink installs like Ubuntu or Mint. So far everyone has said "Arch." OP is on Hyperland which will be much more bare bones than KDE (KDE is a "kitchen sink" DE) and I don't use a DE as well.

**Comment by sonic2kk** [comment]
it seems `libgthread` is included as part of the `glib2` package. This is a dependency of quite a lot of packages that I have installed.

> As for Arch based "Distrobutions"

I am using vanilla Arch and I have this package, by the way. Much of KDE depends on this. In fact, [Hyprland depends on this](https://gitlab.archlinux.org/archlinux/packaging/packages/hyprland/-/blob/4efcaaf25bff60545b019b7824667f37dcb3a7cc/PKGBUILD#L17).

<hr>

I wonder if OP is having a different issue than @ToRRent1812. Perhaps a similar cause, but a different missing library.

**Comment by nPHYN1T3** [comment]
KDE is a kitchen sink so I'd be surprised if anything was missing when KDE is installed. I'd say yes it's a different issue because me and OP don't get any errors about anything missing. It goes through the Loaded ctmod XXXX list then just ends never finishing.

**Comment by DavidoTek** [comment]
> on my end, it says, it's missing libgthread-2_0-0 so I just downloaded it with package manager.
> I'd say yes it's a different issue because me and OP don't get any errors about anything missing. It goes through the Loaded ctmod XXXX list then just ends/hangs.

Sounds like a different error to me too. @ToRRent1812 did it just print the error when starting ProtonUp-Qt normally or did you enable any debugging output?

---

Please try running the following commands to see if it is related to X11/Wayland. With `QT_DEBUG_PLUGINS=1`, it should print a lot more details. Please upload the output to https://gist.github.com/ and share it here.

```bash
QT_QPA_PLATFORM=xcb QT_DEBUG_PLUGINS=1 ./ProtonUp-Qt-2.11.1-x86_64.AppImage

QT_QPA_PLATFORM=wayland QT_DEBUG_PLUGINS=1 ./ProtonUp-Qt-2.11.1-x86_64.AppImage
```

**Comment by nPHYN1T3** [comment]
I ran that for giggles and after the Loaded ctmod list I get:

```
qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb_glx")
qt.core.plugin.factoryloader: looking at "qt6.conf"
qt.core.plugin.loader: Failed to find metadata in lib /tmp/.mount_ProtonrJSg1a/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/xcbglintegrations/qt6.conf: '/tmp/.mount_ProtonrJSg1a/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/xcbglintegrations/qt6.conf' is not a valid ELF object (invalid signature)
qt.core.plugin.factoryloader: "Failed to extract plugin meta data from '/tmp/.mount_ProtonrJSg1a/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/xcbglintegrations/qt6.conf': '/tmp/.mount_ProtonrJSg1a/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/xcbglintegrations/qt6.conf' is not a valid ELF object (invalid signature)" 
         not a plugin
qt.core.plugin.factoryloader: checking directory path "/tmp/.mount_ProtonrJSg1a/usr/bin/xcbglintegrations" ...
qt.core.library: "/tmp/.mount_ProtonrJSg1a/usr/local/lib/python3.10/dist-packages/PySide6/Qt/plugins/xcbglintegrations/libqxcb-glx-integration.so" loaded library

```

That's the only "failed|error" I see.

**Comment by 123Daktary** [comment]
I am running Hyprland as my WM and I don't use any proper DE on my machine to be able to test both X11 and Wayland sessions. At the same time, I have different Gnome and KDE GUI applications installed so, I guess the dependencies should be there. `glib2` and `lib32-glib2` are installed on my machine.

To exclude this issue, on a secondary Arch install, I installed the `protonup-qt` AUR package (v2.11.1) and it runs fine on my system. On the same system, with the AUR package installed, the AppImage version it will hang so I guess it's not dependent on what is installed on the system.

In the meantime, I also tested the v2.11.1 AppImage on a Linux Mint 21 machine running Cinnamon 6 and 6.8 kernel. It ran fine on both the X11 session and their experimental Wayland session.

Looking at the debugging commands that were provided, it seems that I'm getting errors even for the cases where the application is working fine. The only case that doesn't have any errors is the AUR package. From what I can see, there's no difference if I set the env variable to either `wayland` or `xcb`.

[Here](https://gist.github.com/123Daktary/8a31432be829246712f7db17a1afe95a) is the output for the 5 setups that I used to test this. Hopefully this helps.

**Comment by nPHYN1T3** [comment]
Yeah installing from the AUR works.

**unrelated: testing from the AUR it also launched "bright." How do you get this to adhere to the set qt theme?

**Comment by Techwolf** [comment]
I did a quick debug run and the gist is at https://gist.github.com/Techwolf/2308e4da78bb4ca328a42c2f40269f9b

**Comment by LiamDawe** [comment]
This seems to be the same problem with the latest 2.12 AppImage release on Steam Deck (SteamOS 3.7 Preview).

It gets to "Loaded ctmod DXVK (nightly)" in terminal and no UI comes up.

**Comment by sonic2kk** [comment]
This is really a shot in the dark but recently I ran into an issue when trying to run an AppImage for modding OpenMW and it would not function. It was caused by AppImageLauncher.

I wonder if, potentially, the same issue is happening here. I don't think it resolved it fully for me, but I think others in the past with problematic AppImages have had success with setting `APPIMAGELAUNCHER_DISABLE=1` before launching their AppImage.

So for ProtonUp-Qt, it may be worth trying to run with `APPIMAGELAUNCHER_DISABLE=1 ./ProtonUp-Qt.v2.12.0-x86_64.AppImage` (or equivalent filename). It may not fully rule out AppImageLauncher being the culprit though; my fix was to uninstall it entirely, but on some systems and setups that is not feasible, and I don't have enough confidence to ask people to try uninstalling to see if that works :-)

<hr>

Fwiw, v2.12.0 AppImage works fine over here on Arch Linux, as does v2.11.1.

**Comment by nPHYN1T3** [comment]
Appimagelauncher is not installed on my system. So no it's not the cause.

**Comment by nPHYN1T3** [comment]
East Side, West Side, Py Side...can't we just all get along!?

**Comment by freak2fast4u** [comment]
Did you actually get around to releasing the AppImage for v2.12.1 ? I can't see it on the releases page : https://github.com/DavidoTek/ProtonUp-Qt/releases/ , even though the source tag is there. 

This bug (no UI being displayed) hit me on Steam OS 3.7.x beta with 2.12.0, and flathub only has 2.11.1 available, which doesn't have umu support, but the UI works. 
I'm stuck between a rock and a hard place here atm. 
As a side question, do you happen to know what the hold-up is over at flathub ?

Thank you for your amazing job with this tool anyhow, it's been super handy up until now <3

**Comment by sonic2kk** [comment]
>  As a side question, do you happen to know what the hold-up is over at flathub ?

Releases on Flathub are tested and released after some time to assess compatibility and if any Flatpak-specific changes need to be made (such as adding paths or adjusting permissions to manifest are needed, runtime bumps, etc). ProtonUp-Qt releases on Flathub are not and have never been immediate following a new release. If I recall it usually takes ~2 weeks.

**Comment by nPHYN1T3** [comment]
I can't say I have issues with any other AppImages I use.

@freak2fast4u your best bet is enable the AUR. I've only got one friend with a Steam Deck and I helped him do it but it was a few years ago. The AUR builds work, the AppImage is likely borked for a while yet.

**Comment by freak2fast4u** [comment]
@sonic2kk , @nPHYN1T3 : thanks for your insights ! After jumping through hoops trying to build the AppImage myself without success ... I resorted to creating a python venv and running ProtonUp-Qt from source, and it works \o/ 
That's fine by me, it's only a stop-gap while waiting for flathub to be updated ;) The theming is b0rked but I can live with it.

-----
On the topic of building my own AppImage from source ... several dependencies were missing from the appimage-builder instructions (git, apt, dpkg and fuse were missing for me, on any arch-based distro I loaded, on top of the documented dependencies) and some build script somewhere still tries to use the apt-key command, which is deprecated and not even included in recent apt packages. 
Even after creating a placeholder script as /usr/bin/apt-key with an alternate command inside to honor a DEPENDS_ON check, an .AppImage file is produced, but it won't start because for some reason it is missing module PySide6.
There's a bunch of "interpreter couldn't be found inside AppDir" messages for sh, perl, and python in the logs as well ... 

I'm not sure how much of this can be alleviated by adjusting the AppImageBuilder.yml or requirements.txt files ... I suspect the appimage-builder tool itself needs patching, but I haven't gone down that rabbit hole yet :p
Anyhow, just running the "appimage-builder" tool from the ProtonUp-Qt source root isn't enough to produce a working AppImage, wether I use the docker version, the appimage version, or even the aur version of appimage-builder.

How do you guys build it ?

**Comment by sonic2kk** [comment]
To my knowledge, the AppImage is built via [GitHub Actions CI](https://github.com/DavidoTek/ProtonUp-Qt/actions/runs/14157857004) against an [Ubuntu 20.04 image](https://github.com/DavidoTek/ProtonUp-Qt/actions/runs/14157857004/workflow#L10).

[The README has instructions for building an AppImage](https://github.com/DavidoTek/ProtonUp-Qt?tab=readme-ov-file#build-appimage) but I don't believe I've ever followed them, maybe once a very long time ago. I can't vouch for them though 😅

**Comment by freak2fast4u** [comment]
Ayoooo got myself a working 2.12.1 AppImage, thank for the pointers @sonic2kk ! 
Targetting ubuntu 22.04 did the trick :) 

Here's for anyone interested : https://drive.proton.me/urls/CA08D7PARG#Djvcg3iD02aJ
I'll document my exact process later in the day, gotta go, see you later :)

**Comment by 123Daktary** [comment]
Interesting. When I tried building the AppImage, I only used the AppImage version of the appimage-builder project. It worked fine on Mint 21.3 (based on Ubuntu Jammy - 22.04). I just put the AppImage inside the project folder and executed it. It does however output a lot of warnings.

I also tested this method on Arch, but it didn't work. Couldn't get that to work with newer versions of Mint / Ubuntu either. From what I can determine, something gets added to the package with the wrong path and / or python version and I couldn't determine where that issue is coming from. The AppImage gets generated but it fails to run with different generic messages.

In either case, my knowledge on this topics is fairly limited. Glad to hear you could do a full build.
